name: MacOS app

on: push
env:
  UTM_VERSION: 0.8.1
  TME_VERSION: master

jobs:
  build:
    runs-on: macos-10.14
    steps:
      - name: Check-out the repo under ${{GITHUB_WORKSPACE}}
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install build tools
        run: |
          brew install boost swig xerces-c
          pip install -U pip
          pip install wheel pyinstaller PyQt5 Markdown

      - name: Build utm ${{UTM_VERSION}}
        run: |
          git clone https://gitlab.cern.ch/cms-l1t-utm/utm.git
          cd utm
          git checkout ${UTM_VERSION}
          make all CPPFLAGS='-DSWIG -DNDEBUG'

      - name: Build tm-grammar
        run: |
          source utm/setup.sh
          git clone https://github.com/cms-l1-globaltrigger/tm-grammar.git
          cd tm-grammar
          git checkout ${UTM_VERSION}
          python setup.py bdist_wheel
          pip install dist/*.whl
            
      - name: Build tm-table
        run: |
          source utm/setup.sh
          git clone https://github.com/cms-l1-globaltrigger/tm-table.git
          cd tm-table
          git checkout ${UTM_VERSION}
          python setup.py bdist_wheel
          pip install dist/*.whl

      - name: Build tm-eventsetup
        run: |
          source utm/setup.sh
          git clone https://github.com/cms-l1-globaltrigger/tm-eventsetup.git
          cd tm-eventsetup
          git checkout ${UTM_VERSION}
          python setup.py bdist_wheel
          pip install dist/*.whl
            
      - name: Build tm-python
        run: |
          source utm/setup.sh
          git clone https://github.com/cms-l1-globaltrigger/tm-python.git
          cd tm-python
          git checkout ${UTM_VERSION}
          python setup.py install
            
      - name: Build tm-editor
        run: |
          source utm/setup.sh
          git clone https://github.com/cms-l1-globaltrigger/tm-editor.git
          cd tm-editor
          git checkout macos
          echo "UTM_ROOT=$UTM_ROOT"
          echo "UTM_XSD_DIR=$UTM_XSD_DIR"
          pyinstaller macos_app.spec
          
      - name: Build DMG image
        run: |
          mkdir -p dmg/tm-editor-${TME_VERSION}
          mv tm-editor/dist/tm-editor.app dmg/tm-editor-${TME_VERSION}
          hdiutil create dmg/tmp.dmg -ov -volname "tm-editor-${TME_VERSION}" -fs HFS+ -srcfolder "dmg/tm-editor-${TME_VERSION}/"
          hdiutil convert dmg/tmp.dmg -format UDZO -o dmg/tm-editor-${TME_VERSION}.dmg

      - uses: actions/upload-artifact@v2
        with:
          name: tm-editor-${{TME_VERSION}}.dmg
          path: dmg/tm-editor-${{TME_VERSION}}.dmg
